language: ruby
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - RACK_ENV=test bundle exec rake db:create
  - RACK_ENV=test bundle exec rake db:migrate
script:
  - RACK_ENV=test bundle exec rspec
env:
  - AWS_REGION=us-east-1
